services:
  hejotrade:
    build:
      context: https://github.com/Mogyi6/HEJOTRADE.git#main
      dockerfile: hejotrade/Dockerfile

    container_name: hejotrade-web

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
